### ISSUE TITLE
想问一下如何配置这个项目

### ISSUE THREAD

**Issue by QuLiao1117** [WilliamYinwei/TreeATE#11]
并没有在readme文档中查找到如何从0开始使用这个项目，想问一下python只能用python2吗？具体该如何部署

**Comment by WilliamYinwei** [comment]
是的，目前仅支持Python 2.7版本。你提到的部署是否是编译后如何打包的还是？

**Comment by QuLiao1117** [comment]
已经用网盘的exe成功安装了，不过demo均未运行成功。之前按照readme中编译也未成功

**Comment by WilliamYinwei** [comment]
可以加入QQ群进一步沟通问题细节。针对该问题也更新了Readme，参见32bit分支，后续会合并到master
